### ISSUE TITLE
include('Hostname/Com.php'), no such file or directory

### ISSUE THREAD

**Issue by demonkoryu** [EvanDotPro/EdpSuperluminal#11]
I'm having a problem with PHP classes like `Zend\Validator\Hostname`, which dynamically include resource-type PHP files relative to their own path. The error occurs here:

``` php
$regexChars += include ($this->validIdns[strtoupper($this->tld)]);
```

**Comment by wiktor-obrebski** [comment]
yeah, this make this module unusable when you make simple email validation somewhere.

**Comment by demonkoryu** [comment]
I'll have to rework the commit above; because it contains a private constant APPLICATION_ZF2_LIB_ROOT.

**Comment by demonkoryu** [comment]
Well, I found no other way than to have the ZF2 library root to be defined somewhere. Or is there...?

**Comment by grizzm0** [comment]
This has now been fixed in the ZF2 code by adding **DIR** to the validator path.
https://github.com/zendframework/zf2/commit/526de7d1fb3798a574fc8684dc4748167b0700b5

**Comment by EvanDotPro** [comment]
Per @grizzm0's comment, I'm going to close this issue if it's no long a problem. Feel free to re-open it if you're still seeing an issue after updating ZF2.
