### ISSUE TITLE
Cannot get it to run with ZF 2.2.2

### ISSUE THREAD

**Issue by RalfEggert** [EvanDotPro/EdpSuperluminal#19]
When I call a page in my browser like http://yourapp/?EDPSUPERLUMINAL_CACHE I always get an error, telling me that the page was aborted. I tried to track this down and figured out, that line 109 starts the trouble.

https://github.com/EvanDotPro/EdpSuperluminal/blob/master/Module.php#L109

Precisely, as soon as $r->getDeclaringFile() is called, the error is shown.

**Comment by Ocramius** [comment]
Looks like some problem with an internal PHP class - did you try-catch it?

**Comment by RalfEggert** [comment]
Try-Catch is not catching any Exception at all. PHP Version is 5.3.3.

**Comment by Ocramius** [comment]
Oh, I see... `$r->getDeclaringFile()`, probably returns `NULL` or `false` on internal PHP classes, so `$r->getDeclaringFile()->getUses()` fails. You should probably apply a simple check there.

**Comment by RalfEggert** [comment]
I have debugged a little more and located the problem within the scan() method of Zend\Code\Scanner\TokenArrayScanner:

https://github.com/zendframework/zf2/blob/master/library/Zend/Code/Scanner/TokenArrayScanner.php#L291

Looking at that method I felt a little lost and stopped my debugging. 

A simple check is quite hard to implement since the call of $r->getDeclaringFile() processes the error...

**Comment by RalfEggert** [comment]
Seems to be a memory_limit issue. After rising the memory_limit the creation of the cache file works.
