### ISSUE TITLE
Fatal error: Cannot redeclare class Zend\Loader\SplAutoloader

### ISSUE THREAD

**Issue by alexander-torosh** [EvanDotPro/EdpSuperluminal#2]
Maked application from latest ZendSkeletonApplication with --recursive, added your EDPSUPERLUMINAL,

<?php
chdir(dirname(**DIR**));

define('ZF_CLASS_CACHE', 'data/cache/classes.php.cache');
if (file_exists(ZF_CLASS_CACHE)) require_once ZF_CLASS_CACHE;

require_once (getenv('ZF2_PATH') ?: 'vendor/ZendFramework/library') . '/Zend/Loader/AutoloaderFactory.php';
Zend\Loader\AutoloaderFactory::factory(array('Zend\Loader\StandardAutoloader' => array()));

.....
?>

Error stack:

Fatal error: Cannot redeclare class Zend\Loader\SplAutoloader in D:\xampp\htdocs\zf2\vendor\ZendFramework\library\Zend\Loader\SplAutoloader.php on line 31
# Time    Memory  Function    Location

1   0.0005  346080  {main}( )   ..\index.php:0
2   0.0389  5201696 require_once( 'D:\xampp\htdocs\zf2\vendor\ZendFramework\library\Zend\Loader\AutoloaderFactory.php' )    ..\index.php:7
3   0.0390  5208392 require_once( 'D:\xampp\htdocs\zf2\vendor\ZendFramework\library\Zend\Loader\SplAutoloader.php' )    ..\AutoloaderFactory.php:24

**Comment by EvanDotPro** [comment]
Can you please pull the latest master and see if you're still experiencing this issue? Thanks.

**Comment by alexander-torosh** [comment]
I pulled latest master and this issue has been resolved.
But, when I enabled SpiffyDoctrineORM Module and tried /?buildCache=1, new issue came on:

Fatal error: Cannot redeclare class Doctrine\ORM\Mapping\Annotation in D:\xampp\htdocs\zf2\vendor\SpiffyDoctrineORM\vendor\doctrine2-orm\lib\Doctrine\ORM\Mapping\Annotation.php on line 22

**Comment by EvanDotPro** [comment]
Interesting.. I will look into this. On a side note, SpiffyDoctrine has been ported over to an official ZF2 module under the Doctrine project: [DoctrineModule](https://github.com/doctrine/DoctrineModule).

**Comment by alexander-torosh** [comment]
Great thanks for your development.
It's good news.

**Comment by EvanDotPro** [comment]
I'm going to mark this as resolved until I hear otherwise.
