### ISSUE TITLE
What's the difference between this module and the classmap generator?

### ISSUE THREAD

**Issue by fabwu** [EvanDotPro/EdpSuperluminal#29]

**Comment by mhujer** [comment]
Classmap autoloader just speeds up file searching by providing "absolute" paths.
This module, on the other hand, puts all loaded classes in one file, so the app then includes one file instead of hundreds.

**Comment by ThaDafinser** [comment]
Try it and believe your eyes :-)

**Comment by fabwu** [comment]
Thanks for this good explanation! My site starts like a rocket... :+1:
