### ISSUE TITLE
Any way to use it where memory is not sufficient?

### ISSUE THREAD

**Issue by ionutfechete** [EvanDotPro/EdpSuperluminal#32]
On the live server it gives : "Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in" ....if i run it locally, and then upload all the files will it work? or do you have any other ideas? thanks!

**Comment by ThaDafinser** [comment]
@IonutPerfectWeb you cant do it locally and then upload it (since the paths are converted to absolute paths)

You can change your memory_limit for just one request:
http://stackoverflow.com/questions/561066/php-fatal-error-allowed-memory-size-of-134217728-bytes-exhausted-codeigniter

**Comment by ionutfechete** [comment]
I do not think i can use ini_set in godaddy though....thanks anyway! I'm going to close this..and generate it locally, then modify manually. thanks for your help!
