### ISSUE TITLE
benchmarks?

### ISSUE THREAD

**Issue by toneplex** [EvanDotPro/EdpSuperluminal#4]
I'm very interested in this module, but was wondering if you could give some stats on how much this has improved speed of your app?

**Comment by tomasfejfar** [comment]
Depends on complexity and number of classes. Good idea would maybe add a whitelist for classes - so that you don't cache stuff, that is used only seldom.

**Comment by EvanDotPro** [comment]
As @tomasfejfar said, the benchmarks are relative to the complexity of a given page. However, I can say on the skeleton with APC enabled, the performance gain is _very_ significant.
