### ISSUE TITLE
Minify the resulting file

### ISSUE THREAD

**Issue by tomasfejfar** [EvanDotPro/EdpSuperluminal#6]
I tried to [port your module](https://github.com/tomasfejfar/ZF1-superluminal) to ZF1 and it quite works - needs some more testing though. 

I noticed that the resulting file can be so big, it actually slows some pages down (just because of HDD read speed - 12MB file on 30MB/s drive takes 500ms). I used php's php_strip_whitespace function. The resulting file was much smaller and it improved the load speed on my 5400rpm drive. I have not tested it on performant server HDD.

**Comment by EvanDotPro** [comment]
This is a good idea -- I'll incorporate php_strip_whitespace while I do some other updates to get this module working again.

**Comment by EvanDotPro** [comment]
Done -- thanks!
