### ISSUE TITLE
syntax error in classes.php.cache (2 closing curly brackets?)

### ISSUE THREAD

**Issue by ghost** [EvanDotPro/EdpSuperluminal#7]
Hi Evan,
I got the following message :
PHP Parse error:  syntax error, unexpected T_VARIABLE, expecting T_FUNCTION in N:\DEV\APPLICATIONS\zf2\data\cache\classes.php.cache on line 2475

each namespace generated is ended by 2 curly brackets so i suppose this can be an issue:

namespace One {
...
}
}
namespace Two {
...
}
}
...

David

PS: i modified Module.php to manage new sharedEvents
$events = $moduleManager->events();
$sharedEvents = $events->getSharedCollections();
$sharedEvents->attach('Zend\Mvc\Application', 'finish', array($this, 'cache'));

**Comment by thew0lf** [comment]
Was this corrected?

**Comment by EvanDotPro** [comment]
This should be fixed now -- tested and working with beta5.
