### ISSUE TITLE
Parse error: syntax error, unexpected '}', expecting '{' in data\cache\classes.php.cache on line 2

### ISSUE THREAD

**Issue by ghost** [EvanDotPro/EdpSuperluminal#9]
Warning: strpos() [function.strpos]: Empty delimiter in vendor\EvanDotPro\EdpSuperluminal\Module.php on line 144

**Comment by EvanDotPro** [comment]
Looking into this -- the strpos() warning on line 144 appears to be an issue when you have a class being cached which has no namespace. Shouldn't be too difficult to fix this. I'm not sure about the parse error on line 2 of the cache file though -- could you provide more context on that?

**Comment by EvanDotPro** [comment]
Turns out it's a bug in Zend\Code. See [ZF2 PR #1797](https://github.com/zendframework/zf2/pull/1797). Once that's merged, this issue should be resolved.
